version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:2024.8.3"
    volumes:
      - ha_conf:/config
      - ../custom_components:/config/custom_components
      - ./configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8124:80
volumes:
  ha_conf: